### ISSUE TITLE
rack-attack-4.3.1 RedisStoreProxy does not accept plain redis

### ISSUE THREAD

**Issue by ryandv** [kickstarter/rack-attack#213]
We are experiencing breakage after upgrading from `rack-attack-4.2.0` to `rack-attack-4.3.1`, due to what appears to be an API incompatibility with `redis`:

```
app error: wrong number of arguments (4 for 3) (ArgumentError)
[...]/bundled_gems/ruby/2.1.0/gems/redis-3.2.0/lib/redis.rb:689:in `setex'
[...]/bundled_gems/ruby/2.1.0/gems/rack-attack-4.3.1/lib/rack/attack/store_proxy/redis_store_proxy.rb:22:in `write'
[...]/bundled_gems/ruby/2.1.0/gems/rack-attack-4.3.1/lib/rack/attack/cache.rb:53:in `do_count'
[...]/bundled_gems/ruby/2.1.0/gems/rack-attack-4.3.1/lib/rack/attack/cache.rb:19:in `count'
[...]/bundled_gems/ruby/2.1.0/gems/rack-attack-4.3.1/lib/rack/attack/throttle.rb:27:in `[]'
[...]/bundled_gems/ruby/2.1.0/gems/rack-attack-4.3.1/lib/rack/attack.rb:58:in `block in throttled?'
[...]/bundled_gems/ruby/2.1.0/gems/rack-attack-4.3.1/lib/rack/attack.rb:57:in `each'
[...]/bundled_gems/ruby/2.1.0/gems/rack-attack-4.3.1/lib/rack/attack.rb:57:in `any?'
[...]/bundled_gems/ruby/2.1.0/gems/rack-attack-4.3.1/lib/rack/attack.rb:57:in `throttled?'
[...]/bundled_gems/ruby/2.1.0/gems/rack-attack-4.3.1/lib/rack/attack.rb:102:in `call'

```

Previously, we were able to pass an instance of `Redis` from version `3.2.0` of the `redis` gem
to `Rack::Attack`, which satisfies the version constraint provided in the [README](https://github.com/kickstarter/rack-attack/blob/v4.3.1/README.md):

```rb
Rack::Attack.cache.store = Rack::Attack::StoreProxy::RedisStoreProxy.new(
  Redis.new(some_redis_config)
)
```

The above configuration appears to have been recommended by others in a previous [issue](https://github.com/kickstarter/rack-attack/issues/102#issuecomment-66176688).

However, after [this commit](https://github.com/kickstarter/rack-attack/commit/dc1b6bf687bbb6c93a3f5b790eb9a0083a1e6bc0#diff-3d0e57d4b76fc949e3de00ea0a5bed8f), it appears that the contract of `RedisStoreProxy` was changed to now depend on an instance of `Redis::Store` and not `Redis`, as only `Redis::Store` from the `redis-store-1.1.5` gem
supports the fourth `raw: true` parameter introduced by the aforementioned commit.

This issue has been reported previously (see https://github.com/kickstarter/rack-attack/issues/136 and https://github.com/kickstarter/rack-attack/issues/190). 

It appears that `rack-attack` now depends on `redis-store` extensions to the interface, which is breaking older configurations that pass a plain `redis` instance. Can `redis` be preserved as a valid store for the `RedisStoreProxy`, to support these pre-existing configurations?

Thanks!

**Comment by rietta** [comment]
Ran into the same issue. And rack-attack-4.2 has a CVE.

**Comment by fabianoarruda** [comment]
I'm getting this error using rack-attack 4.4.1 and redis gem v3.3.5. I'm not sure but per @ryandv comment, I would have to update my config file to fix the error? This is how it is currently set up in my initializer:

```ruby
Rack::Attack.cache.store = Rack::Attack::StoreProxy::RedisStoreProxy.new(Redis.current)
```

Here is the backtrace:

```
ArgumentError: wrong number of arguments (given 4, expected 3)
/gems/redis-3.3.5/lib/redis.rb:767 in setex
/opt/rbenv/versions/2.3.1/lib/ruby/2.3.0/delegate.rb:83 in method_missing
/gems/rack-attack-4.4.1/lib/rack/attack/store_proxy/redis_store_proxy.rb:22 in write
/gems/rack-attack-4.4.1/lib/rack/attack/cache.rb:53 in do_count
/gems/rack-attack-4.4.1/lib/rack/attack/cache.rb:19 in count
/gems/rack-attack-4.4.1/lib/rack/attack/throttle.rb:27 in []
/gems/rack-attack-4.4.1/lib/rack/attack.rb:59 in block in throttled?
/gems/rack-attack-4.4.1/lib/rack/attack.rb:58 in any?
/gems/rack-attack-4.4.1/lib/rack/attack.rb:58 in throttled?
/gems/rack-attack-4.4.1/lib/rack/attack.rb:103 in call
```

**Comment by asheynkman** [comment]
anyone ever figured out the fix for this issue?

**Comment by allam-matsubara** [comment]
I'm still facing this issue with rack-attack version 5.0.1 and redis-server 2.8.4.

**Comment by ryandv** [comment]
There is a third option, which I've submitted as a [pull request](https://github.com/kickstarter/rack-attack/pull/348).

**Comment by grzuy** [comment]
Hi @ryandv, thank you very much for detailed issue report.

From what I understand `RedisStoreProxy` was always meant to make `redis-store` work for rack-attack, not explicitly plain `redis`. If plain `redis` worked occasionally in conjunction with `RedisStoreProxy` sounds like it was just a coincidence.

That said, I'll tag this `feature request` instead of `error report`.

**Comment by grzuy** [comment]
For the record, plain `Redis` supported added in `rack-attack 5.4.0`.

**Comment by laneystroup** [comment]
@gruzy, I am using a config similar to the above, and am getting the same error message. I can reproduce the last four lines of the traceback in both version 4.3.0 and 5.4.0 from a rails console, as well, with the following:

`
s=Rack::Attack::StoreProxy::RedisStoreProxy.new(Redis.current)
r=Redis.new(db:1)
s.read(“test_key")
s.write("test_key", "test_value", :expires_in => 1)
`

Is this the expected behavior?

**Comment by laneystroup** [comment]
OK, I get it: the correct way to interact with a "Redis" instance (vs. Redis::Store) is to use the new Rack::Attack::StoreProxy::RedisProxy class, as this class drops the fourth argument (i.e. "raw: true" that causes the original configuration above to throw the "wrong number of arguments" (see [this commit](https://github.com/kickstarter/rack-attack/commits/0f6ef47683c4dbcabc94007391e3900f214c8e7d))

@grzuy, thanks for merging this in! Hopefully this will help any others who stumble across this issue.

**Comment by grzuy** [comment]
@laneystroup That's right :dart: 

Kudos to @bfad and @ryandv for making it happen :clap:
