### ISSUE TITLE
Support RedisCacheStore (new in Rails 5.2)

### ISSUE THREAD

**Issue by brian-kephart** [kickstarter/rack-attack#281]
After upgrading my app to Rails 5.2.0rc1, I'm occasionally getting the following error:
`Redis::CommandError: ERR value is not an integer or out of range`

Google says this error is caused by not passing the `raw` option when writing to Redis, then later incrementing the key. This appears to be fixed in this library for other forms of Redis caching, but not for the new ActiveSupport::Cache::RedisCacheStore.

Previous (working) config:
Ruby 2.5.0
Rails 5.1.4
ReadThisStore
Hiredis (driver)

Current (non-working) config:
Ruby 2.5.0
Rails 5.2.0rc1
RedisCacheStore
Hiredis (driver)

**Comment by grzuy** [comment]
Hi Brian,

I am trying to understand exactly where this is issue is coming from.

Can you share what your rack-attack configuration looks like after upgrading to rails 5.2?
And if possible also the stacktrace for the `Redis::CommandError: ERR value is not an integer or out of range` exception?

Thank you!

**Comment by grzuy** [comment]
Hi Brian,

Thanks for sharing those details!

I do understand the issue with `increment`ing non-raw value. Despite that, still trying to understand how would you hit that exception while using latest rack-attack version.

**Comment by brian-kephart** [comment]
Strangely, I can't reproduce the error on command. It's an occasional thing. The stack trace above was part of a series of consecutive errors. Before and after the series of errors, the app worked fine with the same request.

This is with a brand new Rails app, just showing the "Yay! You're on Rails!" page.

**Comment by brian-kephart** [comment]
Test app is a new Rails 5.2 app using Ruby 2.5.1. Other details:
- `gem 'rack-attack'` and `gem 'redis'` added to Gemfile
- `config.middleware.use Rack::Attack` added to config/application.rb
- This code in config/initializers/rack-attack.rb:
```ruby
class Rack::Attack
  throttle('req/ip', :limit => 60, :period => 2.minutes) do |req|
    req.ip # unless req.path.start_with?('/assets')
  end

  throttle('logins/ip', :limit => 5, :period => 20.seconds) do |req|
    if req.path == '/login' && req.post?
      req.ip
    end
  end

  throttle("logins/email", :limit => 5, :period => 20.seconds) do |req|
    if req.path == '/login' && req.post?
      # return the email if present, nil otherwise
      req.params['email'].presence
    end
  end
end

```
- This code in config/environments/development.rb:
```ruby
NOISY_ERROR_HANDLER = ->(method:, returning:, exception:) { raise exception }
config.action_controller.perform_caching = true

config.cache_store = :redis_cache_store, { error_handler: NOISY_ERROR_HANDLER }
```
Please note that the original error report was from my production environment, so this has been observed in both environments.

**Comment by brian-kephart** [comment]
Ok, so I think I fixed the wrong thing in my pull request. My errors didn't go away because of the new cache store proxy, they went away because after I disabled rack-attack, I had some *different* Redis errors that I solved by setting `reconnect_attempts: 1` in my cache config.

I tried using my PR branch in the test app. The errors were different, but I still got errors in the same situation as when I used the current version. With either version of the gem, the errors went away when I set the cache config as described above.

This explains the intermittent behavior of the errors in production, because they were the result of Redis disconnecting momentarily. They happened to resemble the errors caused by other means, so my search led me to bad conclusions.

It might be worth documenting this setting for users of RedisCacheStore, but it doesn't seem like there's anything to fix in rack-attack itself. Sorry for the wild goose chase. I'll close the PR.

Like I mentioned, the errors were different when using the store proxy from my PR. Here's the stack trace, if you're still interested in it for any reason:
```
Redis::ConnectionError (Connection lost (ECONNRESET)):

redis (4.0.1) lib/redis/client.rb:255:in `rescue in io'
redis (4.0.1) lib/redis/client.rb:247:in `io'
redis (4.0.1) lib/redis/client.rb:259:in `read'
redis (4.0.1) lib/redis/client.rb:186:in `block in call_pipelined'
redis (4.0.1) lib/redis/client.rb:229:in `block (2 levels) in process'
redis (4.0.1) lib/redis/client.rb:366:in `ensure_connected'
redis (4.0.1) lib/redis/client.rb:219:in `block in process'
redis (4.0.1) lib/redis/client.rb:304:in `logging'
redis (4.0.1) lib/redis/client.rb:218:in `process'
redis (4.0.1) lib/redis/client.rb:185:in `call_pipelined'
redis (4.0.1) lib/redis/client.rb:155:in `block in call_pipeline'
redis (4.0.1) lib/redis/client.rb:291:in `with_reconnect'
redis (4.0.1) lib/redis/client.rb:153:in `call_pipeline'
redis (4.0.1) lib/redis.rb:2307:in `block in pipelined'
redis (4.0.1) lib/redis.rb:45:in `block in synchronize'
/Users/briankephart/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
redis (4.0.1) lib/redis.rb:45:in `synchronize'
redis (4.0.1) lib/redis.rb:2303:in `pipelined'
/Users/briankephart/.rvm/gems/ruby-2.5.1/bundler/gems/rack-attack-0351b8be368a/lib/rack/attack/store_proxy/redis_cache_store_proxy.rb:13:in `increment'
/Users/briankephart/.rvm/gems/ruby-2.5.1/bundler/gems/rack-attack-0351b8be368a/lib/rack/attack/cache.rb:54:in `do_count'
/Users/briankephart/.rvm/gems/ruby-2.5.1/bundler/gems/rack-attack-0351b8be368a/lib/rack/attack/cache.rb:18:in `count'
/Users/briankephart/.rvm/gems/ruby-2.5.1/bundler/gems/rack-attack-0351b8be368a/lib/rack/attack/throttle.rb:28:in `[]'
/Users/briankephart/.rvm/gems/ruby-2.5.1/bundler/gems/rack-attack-0351b8be368a/lib/rack/attack.rb:106:in `block in throttled?'
/Users/briankephart/.rvm/gems/ruby-2.5.1/bundler/gems/rack-attack-0351b8be368a/lib/rack/attack.rb:105:in `any?'
/Users/briankephart/.rvm/gems/ruby-2.5.1/bundler/gems/rack-attack-0351b8be368a/lib/rack/attack.rb:105:in `throttled?'
/Users/briankephart/.rvm/gems/ruby-2.5.1/bundler/gems/rack-attack-0351b8be368a/lib/rack/attack.rb:171:in `call'
rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
actionpack (5.2.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.0) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

I'll leave this issue open until I hear whether you think `reconnect_attempts` should be mentioned in the documentation or not. Thanks for your attention on this @grzuy, and sorry if it sucked up your time.

**Comment by grzuy** [comment]
> [...] it doesn't seem like there's anything to fix in rack-attack itself.

Cool

> I'll leave this issue open until I hear whether you think reconnect_attempts should be mentioned in the documentation or not.

I am not sure about that. Feels like something out of the scope of rack-attack to me. It's up to users to set their preferred redis configuration.

> Thanks for your attention on this @grzuy, and sorry if it sucked up your time.

No worries. I think this discussion ended up being useful. We now know rack-attack supports rails 5.2 `RedisCacheStore`. Thanks for taking the time to investigate the issue and being so responsive.

**Comment by orenbnv** [comment]
Having the exact same issue here.
Same stack. 
Rails 5.2. Redis being used as cache store. Also using hiredis. 
Any suggestions?

**Comment by orenbnv** [comment]
When you look at redis, seems like the value being stored is indeed not an integer.
It is:
```
"\u0004\bo: ActiveSupport::Cache::Entry\n:\v@valuei\u0006:\u0015@marshaled_value\"\t\u0004\bi\u0006:\r@version0:\u0010@created_atf\u00161528819338.985056:\u0010@expires_inf\b163"
```

So something is indeed dropping the wrong value.

**Comment by brian-kephart** [comment]
Did you read [this comment](https://github.com/kickstarter/rack-attack/issues/281#issuecomment-390088593) above? In my case, I discovered the problem went away when I added `reconnect_attempts: 0` to my cache config as detailed [here](http://edgeguides.rubyonrails.org/caching_with_rails.html#activesupport-cache-rediscachestore). I was actually experiencing a connection error.

I never did figure out _why_ that seems to work, though. All my reasoning says there's a problem in this gem, but the acceptance tests and my experience using it says it works fine as is. 🤷‍♂️

Do you have a reliable repro?

**Comment by stevegeek** [comment]
Hi all, I have just been experiencing this too. I checked that the redis cache config does not specify the reconnect attempts and as per the docs http://edgeguides.rubyonrails.org/caching_with_rails.html#activesupport-cache-rediscachestore the default should just be 0. It is intermittent and as per other posts clears after some time. (Rails 5.2, Ruby 2.5.1, on Heroku using Heroku Redis)

**Comment by grzuy** [comment]
Hi @stevegeek,

Can you please provide the following info to help debug your issue?

- rack-attack version
- Error stacktrace
- Are you setting `Rack::Attack.cache.store`? If so, what are you assigning?

Thank you! :-)

**Comment by stevegeek** [comment]
@grzuy Sure thing!

`rack-attack (5.2.0)` 

```
[GEM_ROOT]/gems/redis-4.0.1/lib/redis/client.rb:119 :in `call`
 [GEM_ROOT]/gems/redis-4.0.1/lib/redis.rb:735 :in `block in incrby`
 [GEM_ROOT]/gems/redis-4.0.1/lib/redis.rb:45 :in `block in synchronize`
[PROJECT_ROOT]/vendor/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226 :in `mon_synchronize`
 [GEM_ROOT]/gems/redis-4.0.1/lib/redis.rb:45 :in `synchronize`
 [GEM_ROOT]/gems/redis-4.0.1/lib/redis.rb:734 :in `incrby`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:255 :in `block (3 levels) in increment`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:26 :in `with`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:255 :in `block (2 levels) in increment`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:439 :in `failsafe`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:254 :in `block in increment`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache.rb:663 :in `block in instrument`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168 :in `block in instrument`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23 :in `instrument`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168 :in `instrument`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache.rb:663 :in `instrument`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:253 :in `increment`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache.rb:109 :in `block in increment`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache.rb:179 :in `block in bypass_local_cache`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache.rb:186 :in `use_temporary_local_cache`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache.rb:179 :in `bypass_local_cache`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache.rb:109 :in `increment`
 [GEM_ROOT]/gems/rack-attack-5.2.0/lib/rack/attack/cache.rb:55 :in `do_count`
 [GEM_ROOT]/gems/rack-attack-5.2.0/lib/rack/attack/cache.rb:19 :in `count`
 [GEM_ROOT]/gems/rack-attack-5.2.0/lib/rack/attack/throttle.rb:28 :in `[]`
 [GEM_ROOT]/gems/rack-attack-5.2.0/lib/rack/attack.rb:103 :in `block in throttled?`
 [GEM_ROOT]/gems/rack-attack-5.2.0/lib/rack/attack.rb:102 :in `any?`
 [GEM_ROOT]/gems/rack-attack-5.2.0/lib/rack/attack.rb:102 :in `throttled?`
 [GEM_ROOT]/gems/rack-attack-5.2.0/lib/rack/attack.rb:168 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/warden-1.2.7/lib/warden/manager.rb:36 :in `block in call`
 [GEM_ROOT]/gems/warden-1.2.7/lib/warden/manager.rb:35 :in `catch`
 [GEM_ROOT]/gems/warden-1.2.7/lib/warden/manager.rb:35 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/rack-2.0.5/lib/rack/tempfile_reaper.rb:15 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/rack-2.0.5/lib/rack/etag.rb:25 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/rack-2.0.5/lib/rack/conditional_get.rb:25 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/rack-2.0.5/lib/rack/head.rb:12 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/actionpack-5.2.0/lib/action_dispatch/http/content_security_policy.rb:18 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232 :in `context`
 [GEM_ROOT]/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/actionpack-5.2.0/lib/action_dispatch/middleware/cookies.rb:670 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:28 :in `block in call`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:98 :in `run_callbacks`
 [GEM_ROOT]/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:26 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/actionpack-5.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:61 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/actionpack-5.2.0/lib/action_dispatch/middleware/show_exceptions.rb:33 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/railties-5.2.0/lib/rails/rack/logger.rb:38 :in `call_app`
 [GEM_ROOT]/gems/railties-5.2.0/lib/rails/rack/logger.rb:26 :in `block in call`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71 :in `block in tagged`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28 :in `tagged`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71 :in `tagged`
 [GEM_ROOT]/gems/railties-5.2.0/lib/rails/rack/logger.rb:26 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/actionpack-5.2.0/lib/action_dispatch/middleware/remote_ip.rb:81 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/actionpack-5.2.0/lib/action_dispatch/middleware/request_id.rb:27 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/action_dispatch/request_id.rb:12 :in `call`
 [GEM_ROOT]/gems/rack-2.0.5/lib/rack/method_override.rb:22 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/rack-2.0.5/lib/rack/runtime.rb:22 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/actionpack-5.2.0/lib/action_dispatch/middleware/executor.rb:14 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/actionpack-5.2.0/lib/action_dispatch/middleware/static.rb:127 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/rack-2.0.5/lib/rack/sendfile.rb:111 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
 [GEM_ROOT]/gems/actionpack-5.2.0/lib/action_dispatch/middleware/ssl.rb:74 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/probes/middleware.rb:37 :in `call`
[GEM_ROOT]/gems/skylight-core-2.0.1/lib/skylight/core/middleware.rb:83 :in `call`
 [GEM_ROOT]/gems/railties-5.2.0/lib/rails/engine.rb:524 :in `call`
 [GEM_ROOT]/gems/puma-3.11.4/lib/puma/configuration.rb:225 :in `call`
 [GEM_ROOT]/gems/puma-3.11.4/lib/puma/server.rb:632 :in `handle_request`
 [GEM_ROOT]/gems/puma-3.11.4/lib/puma/server.rb:446 :in `process_client`
 [GEM_ROOT]/gems/puma-3.11.4/lib/puma/server.rb:306 :in `block in run`
 [GEM_ROOT]/gems/puma-3.11.4/lib/puma/thread_pool.rb:120 :in `block in spawn_thread`
```

Rack attack initializer
```ruby
module Rack
  class Attack
    if Rails.env.production?
      throttle("csp/ip", limit: 3000, period: 5.minutes) do |req|
        req.ip if req.path.start_with?("/csp-violation-report-endpoint")
      end

      throttle("req/ip", limit: 6000, period: 5.minutes) do |req|
        req.ip unless req.path.start_with?("/csp-violation-report-endpoint")
      end

      throttle("logins/ip", limit: 5, period: 20.seconds) do |req|
        req.ip if req.path == "/accounts/sign_in" && req.post?
      end
    end
  end
end
```

Rails config:
`  config.cache_store = :redis_cache_store, {url: ENV["REDIS_URL"]}`

**Comment by grzuy** [comment]
> rack-attack (5.2.0)

`rack-attack` `5.3.2`, or greater, should fix that problem.

Let me know if it doesn't.

**Comment by stevegeek** [comment]
@grzuy Ah ok thanks, sorry! missed that it was fixed

**Comment by leondmello** [comment]
Seeing this error on the latest version of the gem. `6.2.2`
Dunno why it stored an error value in the first place.
we have a custom wrapper around the Redis cache store. Trying to see if that cause any of this 😕

**Comment by leondmello** [comment]
Figured out our issue. Posting for anyone who has a similar setup.
We extended the base redis cache store with out custom implementation with something like,
```ruby
class CustomRedisCacheStore < ActiveSupport::Cache::RedisCacheStore
```
Since we do that, it bypasses the custom proxy instantiation done via https://github.com/kickstarter/rack-attack/blob/da418806638d0556fe15f20cea20194d4bbb85b3/lib/rack/attack/store_proxy.rb#L15-L18
Because of that, we missed the raw write that this offers
https://github.com/kickstarter/rack-attack/blob/6-stable/lib/rack/attack/store_proxy/redis_cache_store_proxy.rb
Fixed it with a monkey patch
```ruby
class StoreProxy::RedisCacheStoreProxy
    def self.handle?(store)
      store.class.name == BMSRedisCacheStore.name
    end
  end
```
