### ISSUE TITLE
rack-attack 5.3.0 stop working with ActiveSupport::RedisCacheStore if connection pool enabled

### ISSUE THREAD

**Issue by le0pard** [kickstarter/rack-attack#352]
Config from rails env:

```ruby
config.cache_store = :redis_cache_store, {
    url: 'redis://127.0.0.1:6379/0',
    namespace: 'cache',
    compress: true,
    compress_threshold: 1.kilobyte,
    expires_in: 6.hours,
    race_condition_ttl: 10.seconds,
    timeout: 10,
    pool_size: 10,
    pool_timeout: 10,
    reconnect_attempts: 3,
    error_handler: lambda { |method:, returning:, exception:|
      # Report errors to Sentry as warnings
      Raven.capture_exception exception, level: 'warning',
        tags: { method: method, returning: returning }
    }
  }
```

options `pool_size` and/or `pool_timeout` activate pool for redis connections:

https://github.com/rails/rails/blob/b7760eb75a9dd002260a361119aea0b255e1f573/activesupport/lib/active_support/cache/redis_cache_store.rb#L187-L192

Result after update to rack-attack 5.3.0:

```ruby
NoMethodError: undefined method `pipelined' for #<ConnectionPool:0x00007f5aa6765b08>
  from rack/attack/store_proxy/redis_cache_store_proxy.rb:13:in `increment'
  from rack/attack/cache.rb:54:in `do_count'
  from rack/attack/cache.rb:18:in `count'
  from rack/attack/throttle.rb:28:in `[]'
  from rack/attack.rb:106:in `block in throttled?'
  from rack/attack.rb:105:in `any?'
  from rack/attack.rb:105:in `throttled?'
  from rack/attack.rb:176:in `call'
```

**Comment by le0pard** [comment]
@grzuy thanks. I already made PR, which fix this problem https://github.com/kickstarter/rack-attack/pull/353 But do not add tests, just test this on my staging servers.

**Comment by grzuy** [comment]
Thanks!

I already have a reproducing test in mind. I can add that, no worries.

**Comment by grzuy** [comment]
Closed by https://github.com/kickstarter/rack-attack/pull/354
