### ISSUE TITLE
After install: ThreadError: deadlock; recursive locking

### ISSUE THREAD

**Issue by jeremyhaile** [kickstarter/rack-attack#36]
Using Rails 3.2, added rack-attack to Gemfile and bundled. Then created an initializer with only the following rule:

``` ruby
Rack::Attack.throttle("req/ip", :limit => 10, :period => 1) { |req| req.ip }
```

Now when I make any request to my app, I get the following error over and over:

```
ThreadError: deadlock; recursive locking
ruby-2.0.0-p247@project/gems/rack-1.4.5/lib/rack/lock.rb:14:in `lock'
ruby-2.0.0-p247@project/gems/rack-1.4.5/lib/rack/lock.rb:14:in `call'
ruby-2.0.0-p247@project/gems/actionpack-3.2.15/lib/action_dispatch/middleware/static.rb:63:in `call'
ruby-2.0.0-p247@project/gems/sentry-raven-0.6.0/lib/raven/rack.rb:47:in `call'
ruby-2.0.0-p247@project/gems/rack-rewrite-1.3.3/lib/rack/rewrite.rb:20:in `call'
ruby-2.0.0-p247@project/gems/railties-3.2.15/lib/rails/engine.rb:484:in `call'
ruby-2.0.0-p247@project/gems/railties-3.2.15/lib/rails/application.rb:231:in `call'
ruby-2.0.0-p247@project/gems/railties-3.2.15/lib/rails/railtie/configurable.rb:30:in `method_missing'
ruby-2.0.0-p247@project/gems/rack-1.4.5/lib/rack/deflater.rb:13:in `call'
ruby-2.0.0-p247@project/gems/rack-1.4.5/lib/rack/lint.rb:48:in `_call'
ruby-2.0.0-p247@project/gems/rack-1.4.5/lib/rack/lint.rb:36:in `call'
ruby-2.0.0-p247@project/gems/rack-1.4.5/lib/rack/showexceptions.rb:24:in `call'
ruby-2.0.0-p247@project/gems/rack-1.4.5/lib/rack/commonlogger.rb:33:in `call'
ruby-2.0.0-p247@project/gems/sinatra-1.4.3/lib/sinatra/base.rb:212:in `call'
ruby-2.0.0-p247@project/gems/rack-1.4.5/lib/rack/chunked.rb:43:in `call'
ruby-2.0.0-p247@project/gems/rack-1.4.5/lib/rack/content_length.rb:14:in `call'
ruby-2.0.0-p247@project/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:580:in `process_client'
ruby-2.0.0-p247@project/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:660:in `worker_loop'
ruby-2.0.0-p247@project/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `call'
ruby-2.0.0-p247@project/gems/newrelic_rpm-3.6.6.147/lib/new_relic/agent/instrumentation/unicorn_instrumentation.rb:22:in `block (4 levels) in <top (required)>'
ruby-2.0.0-p247@project/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:527:in `spawn_missing_workers'
ruby-2.0.0-p247@project/gems/unicorn-4.7.0/lib/unicorn/http_server.rb:153:in `start'
ruby-2.0.0-p247@project/gems/unicorn-4.7.0/bin/unicorn:126:in `<top (required)>'
ruby-2.0.0-p247@project/bin/unicorn:23:in `load'
ruby-2.0.0-p247@project/bin/unicorn:23:in `<main>'
ruby-2.0.0-p247@project/bin/ruby_noexec_wrapper:14:in `eval'
ruby-2.0.0-p247@project/bin/ruby_noexec_wrapper:14:in `<main>'
```

I'm using redis 3.0.4 driver as my Rails cache.

Other rack middleware I'm using:
- rack-mobile-detect
- rack-p3p
- rack-rewrite
- rack-ssl-enforcer

Any ideas what could be wrong?

**Comment by reidcooper** [comment]
I just encountered a bunch of these issues `ThreadError: deadlock; recursive locking` when using Puma on Heroku, as well as using Sidekiq.

**Comment by grzuy** [comment]
Hi @reidcooper,

Do you have an error stacktrace to share?

Thanks!

**Comment by reidcooper** [comment]
@grzuy Sorry for the delay.

Here is a Sentry link to the error: https://sentry.io/share/issue/6012b18fe942423696f103485c8486f6/

```
ThreadError: deadlock; recursive locking
  from monitor.rb:185:in `lock'
  from monitor.rb:185:in `mon_enter'
  from monitor.rb:224:in `mon_synchronize'
  from redis.rb:45:in `synchronize'
  from redis.rb:2303:in `pipelined'
  from delegate.rb:83:in `method_missing'
  from rack/attack/store_proxy/redis_store_proxy.rb:31:in `increment'
  from rack/attack/cache.rb:49:in `do_count'
  from rack/attack/cache.rb:19:in `count'
  from rack/attack/throttle.rb:27:in `[]'
  from rack/attack.rb:89:in `block in throttled?'
  from rack/attack.rb:88:in `any?'
  from rack/attack.rb:88:in `throttled?'
  from rack/attack.rb:143:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from warden/manager.rb:36:in `block in call'
  from warden/manager.rb:35:in `catch'
  from warden/manager.rb:35:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/etag.rb:24:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/conditionalget.rb:25:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/head.rb:13:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/params_parser.rb:27:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/flash.rb:260:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/session/abstract/id.rb:225:in `context'
  from rack/session/abstract/id.rb:220:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/cookies.rb:560:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from active_record/query_cache.rb:36:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/callbacks.rb:29:in `block in call'
  from active_support/callbacks.rb:88:in `__run_callbacks__'
  from active_support/callbacks.rb:778:in `_run_call_callbacks'
  from active_support/callbacks.rb:81:in `run_callbacks'
  from action_dispatch/middleware/callbacks.rb:27:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/remote_ip.rb:78:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/show_exceptions.rb:30:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rails/rack/logger.rb:38:in `call_app'
  from rails/rack/logger.rb:20:in `block in call'
  from active_support/tagged_logging.rb:68:in `block in tagged'
  from active_support/tagged_logging.rb:26:in `tagged'
  from active_support/tagged_logging.rb:68:in `tagged'
  from rails/rack/logger.rb:20:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from request_store/middleware.rb:19:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/request_id.rb:21:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/methodoverride.rb:22:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/runtime.rb:18:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/timeout/core.rb:122:in `block in call'
  from rack/timeout/support/timeout.rb:19:in `timeout'
  from rack/timeout/core.rb:121:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/static.rb:120:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/sendfile.rb:113:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from action_dispatch/middleware/ssl.rb:24:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from app/middleware/weighted_traffic_splitter.rb:51:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/cors.rb:97:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/heartbeat.rb:45:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from raven/integrations/rack.rb:51:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rails/engine.rb:518:in `call'
  from rails/application.rb:165:in `call'
  from rails/railtie.rb:194:in `public_send'
  from rails/railtie.rb:194:in `method_missing'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from rack/deflater.rb:35:in `call'
  from new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  from puma/configuration.rb:225:in `call'
  from puma/server.rb:624:in `handle_request'
  from puma/server.rb:438:in `process_client'
  from puma/server.rb:302:in `block in run'
  from puma/thread_pool.rb:120:in `block in spawn_thread'
  from logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by grzuy** [comment]
> when using Puma on Heroku, as well as using Sidekiq.

@reidcooper Can you please share a stacktrace of the error but when originating from a sidekiq process? It would be strange if rack-attack is present in those stacktraces, is it?

Thanks!

**Comment by reidcooper** [comment]
@grzuy 

I am unable to find any logging information that connects Rack Attack with Sidekiq. In my `rack_attack.rb`, I have: 

```
throttle('req/ip', limit: 300, period: 5.minutes) do |req|
      req.ip  unless req.path.starts_with?('/sidekiq')
    end
```

Which I want to allow access to `/sidekiq` for admin purposes. We are on Heroku, and our app should be returning the assets (but we use a CDN). 

What I found interesting was my chart in new relic:

- https://i.imgur.com/cz7ckRQ.png
- https://i.imgur.com/c2c6OHo.png

At least I was seeing huge response times from `Rack::Attack#call`. We are using Redis as the Rails' cache. The error stack trace I've attached earlier is the best I can find. 

If there is a better way to try and report on these matters in the future, what I can I do to configure my app to log better errors?

However, like you said, it seems like there is an issue with the communication with Rails' cache, Redis.

**Comment by grzuy** [comment]
> What I found interesting was my chart in new relic:

> https://i.imgur.com/cz7ckRQ.png

In the "Throughput" chart you can see that `Non-Web` traffic has almost frozen. I assume your non-web traffic is background job processing. If that's the case, it is another indication that the problem is probably in redis.

Not sure there's much we can do on rack-attack's side :-/
Wish I could.

> https://i.imgur.com/c2c6OHo.png

In "Breakdown Table", can you somehow break it more so you can see what part of `Rack::Attack#call` is the bottleneck? Maybe that could help to figure out the underlying issue.

**Comment by reidcooper** [comment]
@grzuy 

Unfortunately I am unable to further break down that transaction.

Has Rack Attack had issues in the past when integrating with Puma? Or even when using the Rails cache, such as Redis?

**Comment by grzuy** [comment]
> Unfortunately I am unable to further break down that transaction.

Bummer :-/

> Has Rack Attack had issues in the past when integrating with Puma? Or even when using the Rails cache, such as Redis?

I don't think there's been any other reported issue mentioning deadlocks with puma and/or redis.

**Comment by ostinelli** [comment]
Hi,
we're seeing similar things:

```
vendor/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:185 in lock
vendor/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:185 in mon_enter
vendor/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:224 in mon_synchronize
/gems/redis-4.0.1/lib/redis.rb:45 in synchronize
/gems/redis-4.0.1/lib/redis.rb:734 in incrby
/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:255 in block (3 levels) in increment
/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:26 in with
/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:255 in block (2 levels) in increment
/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:439 in failsafe
/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:254 in block in increment
/gems/activesupport-5.2.0/lib/active_support/cache.rb:663 in block in instrument
/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170 in instrument
/gems/activesupport-5.2.0/lib/active_support/cache.rb:663 in instrument
/gems/activesupport-5.2.0/lib/active_support/cache/redis_cache_store.rb:253 in increment
/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache.rb:109 in block in increment
/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache.rb:179 in block in bypass_local_cache
/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache.rb:186 in use_temporary_local_cache
/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache.rb:179 in bypass_local_cache
/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache.rb:109 in increment
/gems/rack-attack-5.2.0/lib/rack/attack/cache.rb:55 in do_count
/gems/rack-attack-5.2.0/lib/rack/attack/cache.rb:19 in count
/gems/rack-attack-5.2.0/lib/rack/attack/throttle.rb:28 in []
/gems/rack-attack-5.2.0/lib/rack/attack.rb:103 in block in throttled?
/gems/rack-attack-5.2.0/lib/rack/attack.rb:102 in any?
/gems/rack-attack-5.2.0/lib/rack/attack.rb:102 in throttled?
/gems/rack-attack-5.2.0/lib/rack/attack.rb:168 in call
```

We also use sidekiq as background job. Not sure what to look for, any inputs on how we can help is appreciated.

**Comment by grzuy** [comment]
Hi @ostinelli,

Same I answered [above](https://github.com/kickstarter/rack-attack/issues/36#issuecomment-386441028) to Reid.

`rack-attack` doesn't do any explicit mutual exclusion. That is done by `redis` gem via ruby's `monitor` standard library. You can see that in the error stacktrace.

Unfortunately, I can't think of anything we can do on rack-attack's side to help with that :-/

**Comment by ostinelli** [comment]
Ok, thank you @grzuy, will see if there's anything that we can do.

**Comment by reidcooper** [comment]
@grzuy @ostinelli I had to place this bug off to the side for now but this one is puzzling. It does indeed sound correct that Rack Attack is not the culprit of the issue however, it lead me to believe it is something to do with Rails' cache which we are both using Redis.

**Comment by ostinelli** [comment]
We have mitigated the issue by reducing the number of Redis clients in the front-end. I know how this sounds, but moving away from complete AWS S3 clients to just the elements that we need (for instance, the `Aws::Sigv4::Signer` when all we need is a pre-signed url) has had a considerable effect of reducing the number of deadlocks.

**Comment by maxcodes** [comment]
For anyone that stumbles upon this: This error is likely due to Redis being overwhelmed with requests. 

Examples:
- Rack::Attack uses the Rails cache to store IPs, etc. If you configured the Rails cache to use Redis
- `Rails.cache.fetch` or `<% cache do %>` blocks also use the rails cache, which could be using Redis

Either reduce the number of Redis clients (what @ostinelli did), or scale up your Redis to be able to manage more concurrent connections.
