### ISSUE TITLE
v5.4.1: Store needs to respond to #increment

### ISSUE THREAD

**Issue by gencer** [kickstarter/rack-attack#391]
On v5.4.1, I got an error from my CI. Same config and codebase successfully builds with v5.4.0.

```
1) manage page with buckets should open new bucket dialog
--
  | Failure/Error: @app.call(env).tap { \|_status, headers, _body\| headers[X_REQUEST_ID] = req.request_id }
  |  
  | Rack::Attack::MisconfiguredStoreError:
  | Store needs to respond to #increment
```

What could be the reason behind Rack Attack gave me `respond_to?(:increment)` error?

Additional Info:
Ruby v2.5.1 x64 on Linux
```
...
gem 'redis', '~> 4.0'
gem 'redis-namespace'
gem 'redis-rails'
...
```

**Comment by grzuy** [comment]
Are you setting `Rack::Attack.cache.store= ...`?

**Comment by gencer** [comment]
In development, yes. In test and production, no.
```

class Rack::Attack
  Rack::Attack.cache.store = ActiveSupport::Cache::MemoryStore.new if Rails.env.development?

```

**Comment by gencer** [comment]
Rack was using internal cache automatically. Did it changed?

**Comment by grzuy** [comment]
Yes, still using `Rails.cache` by default.

What's your `Rails.cache` set to in `test` environment?

**Comment by gencer** [comment]
I declare cache store as:

```
config.cache_store = :redis_store, 'redis://127.0.0.1:6379/3/cache',
                     { password:   'xxx', pool_size: 5,
        expires_in: 90.minutes }
```

**Comment by grzuy** [comment]
I see.

Do you mind sharing the complete error backtrace please?

**Comment by gencer** [comment]
Here we go:


```
Failures:
--
  |  
  | 1) manage page with buckets should open new bucket dialog
  | Failure/Error: @app.call(env).tap { \|_status, headers, _body\| headers[X_REQUEST_ID] = req.request_id }
  |  
  | Rack::Attack::MisconfiguredStoreError:
  | Store needs to respond to #increment
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-attack-5.4.1/lib/rack/attack/cache.rb:74:in `enforce_store_method_presence!'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-attack-5.4.1/lib/rack/attack/cache.rb:53:in `do_count'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-attack-5.4.1/lib/rack/attack/cache.rb:19:in `count'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-attack-5.4.1/lib/rack/attack/throttle.rb:28:in `matched_by?'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-attack-5.4.1/lib/rack/attack.rb:108:in `block in throttled?'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-attack-5.4.1/lib/rack/attack.rb:107:in `any?'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-attack-5.4.1/lib/rack/attack.rb:107:in `throttled?'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-attack-5.4.1/lib/rack/attack.rb:178:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/tempfile_reaper.rb:15:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/conditional_get.rb:25:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:38:in `call_app'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:26:in `block in call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:26:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # ./lib/middleware/rack_pre_touch_middleware.rb:13:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/static.rb:127:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/secure_headers-6.0.0/lib/secure_headers/middleware.rb:13:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sentry-raven-2.7.4/lib/raven/integrations/rack.rb:51:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/skylight-core-3.0.0/lib/skylight/core/probes/middleware.rb:29:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:524:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/urlmap.rb:68:in `block in call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `each'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-3.9.0/lib/capybara/server/middleware.rb:48:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
  | # /var/lib/buildkite-agent/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by grzuy** [comment]
Thank you for sharing. Cannot get any new clue from looking at the backtrace.

Can you debug when running the failing test which is the value for `Rack::Attack.cache.store.class.name`?

**Comment by gencer** [comment]
Very interestingly, I got `ConnectionPool`.

**Comment by grzuy** [comment]
Oh, I see.

Is `Rails.cache.class.name` equals `ConnectionPool` also in that case?

**Comment by grzuy** [comment]
Are you doing anything special with `config.cache_store` in `config/environments/test.rb`?

**Comment by gencer** [comment]
No. As i posted in first post i've implemented cache store as it is. Also i had a gem called connecion_pool. I will remove that and try again when i am home but im sure nothing special with both in store and test.rb.

**Comment by gencer** [comment]
@grzuy, I have double checked. There is no any special thing regarding to this either in application.rb or test.rb.

**Comment by grzuy** [comment]
Gotcha.

Unfortunately I wasn't able to reproduce the issue on my end with the information you provided so far about your environment :-/

**Comment by grzuy** [comment]
> Very interestingly, I got `ConnectionPool`.

FWIW, the cache class is `ConnectionPool` because you're using `pool_size` option when configuring `cache_store`.

**Comment by grzuy** [comment]
`Rack::Attack` doesn't explicitly support pooled `redis-rails`'s `RedisStore`, see discussion in https://github.com/kickstarter/rack-attack/issues/211#issuecomment-399545556.

If it worked, or appeared to work before, was accidental.

As stated in https://github.com/kickstarter/rack-attack/issues/211#issuecomment-400468399 I encourage anyone using `RedisStore`, which is officially deprecated/unmaintained, to consider migrating to new rails build-in `RedisCacheStore`.

**Comment by gencer** [comment]
@grzuy, yesterday I tried this solution and it did worked. I was going to update here but it seems you already did.

Issue is resolved here.

**Comment by grzuy** [comment]
Cool, thanks for letting us know.

**Comment by HendrikPetertje** [comment]
for people finding this in the future that are on rails 5.2+. 
- `redis_cache` or `redis_store` would need to be renamed to `redis_cache_store`
- `namespace: 'your namespace'` seems to interfere with the ability to increment, etc.
