### ISSUE TITLE
Configuration broken on ruby 2.6.5

### ISSUE THREAD

**Issue by doutatsu** [kickstarter/rack-attack#467]
I've bumped by ruby recently to 2.6.5, and now my rails is not starting up at all. Removing `class Rack::Attack` makes the server run as expected, without issues.

I am using Rails `5.1.7` and rack-attack version `6.1.0`. Here is how my configuration looks like:

```
class Rack::Attack
  # Ignore in development and test environments
  return unless Rails.env.production?

  # Blacklist
  # This IP was by extremely aggressive scraper
  Rack::Attack.blocklist_ip("107.151.148.74")

  ### Configure Cache ###

  # If you don't want to use Rails.cache (Rack::Attack's default), then
  # configure it here.
  #
  # Note: The store is only used for throttling (not blacklisting and
  # whitelisting). It must implement .increment and .write like
  # ActiveSupport::Cache::Store

  # Rack::Attack.cache.store = ActiveSupport::Cache::MemoryStore.new

  ### Throttle Spammy Clients ###

  # If any single client IP is making tons of requests, then they're
  # probably malicious or a poorly-configured scraper. Either way, they
  # don't deserve to hog all of the app server's CPU. Cut them off!
  #
  # Note: If you're serving assets through rack, those requests may be
  # counted by rack-attack and this throttle may be activated too
  # quickly. If so, enable the condition to exclude them from tracking.

  # Throttle all requests by IP (60rpm)
  #
  # Key: "rack::attack:#{Time.now.to_i/:period}:req/ip:#{req.ip}"
  throttle('req/ip', limit: 300, period: 5.minutes) do |req|
    req.ip # unless req.path.start_with?('/assets')
  end

  ### Prevent Brute-Force Login Attacks ###

  # The most common brute-force login attack is a brute-force password
  # attack where an attacker simply tries a large number of emails and
  # passwords to see if any credentials match.
  #
  # Another common method of attack is to use a swarm of computers with
  # different IPs to try brute-forcing a password for a specific account.

  # Throttle POST requests to /users/sign_in by IP address
  #
  # Key: "rack::attack:#{Time.now.to_i/:period}:logins/ip:#{req.ip}"
  throttle('logins/ip', limit: 5, period: 20.seconds) do |req|
    if req.path == '/users/sign_in' && req.post?
      req.ip
    end
  end

  # Throttle POST requests to /users/sign_in by email param
  #
  # Key: "rack::attack:#{Time.now.to_i/:period}:logins/email:#{req.email}"
  #
  # Note: This creates a problem where a malicious user could intentionally
  # throttle logins for another user and force their login requests to be
  # denied, but that's not very common and shouldn't happen to you. (Knock
  # on wood!)
  throttle("logins/email", limit: 5, period: 20.seconds) do |req|
    if req.path == '/users/sign_in' && req.post?
      # return the email if present, nil otherwise
      req.params['email'].presence
    end
  end

  ### Custom Throttle Response ###

  # By default, Rack::Attack returns an HTTP 429 for throttled responses,
  # which is just fine.
  #
  # If you want to return 503 so that the attacker might be fooled into
  # believing that they've successfully broken your app (or you just want to
  # customize the response), then uncomment these lines.
  # self.throttled_response = lambda do |env|
  #  [ 503,  # status
  #    {},   # headers
  #    ['']] # body
  # end
end
```

What happens, is that I get these errors, depending on what's not commented out:
`undefined method 'blocklist_ip' for Rack::Attack:Class (NoMethodError)`
`undefined method 'throttle' for Rack::Attack:Class (NoMethodError)`

**Comment by grzuy** [comment]
Hi @doutatsu ,

Thanks for reporting.

Which was the previous ruby version you were using?

**Comment by doutatsu** [comment]
I was using `2.4.5`

**Comment by grzuy** [comment]
There's no rack-attack 6.0.1.
Is 6.1.0 what you meant?

**Comment by doutatsu** [comment]
Ah yup, sorry about the typo!

**Comment by grzuy** [comment]
Hi @doutatsu ,

Thanks for the info.

Wasn't able to reproduce the issue on a clean rails app: https://github.com/grzuy/test_app_rack_attack_467/commits/master.

Feel free to fork and try reproduce by adding more stuff to the mix...

**Comment by doutatsu** [comment]
That's for confirming, I'll continue looking into it, must be something else interfering on the middleware

**Comment by corroded** [comment]
@doutatsu have you managed to investigate? I am currently investigating as well. Weird - `throttle` works but the other configuration stuff are broken i.e. 

```
NoMethodError:
  undefined method `configuration' for Rack::Attack:Class
# ./config/initializers/rack_attack.rb:82:in `<main>'
```

```
NoMethodError:
  undefined method `throttled_response_retry_after_header=' for Rack::Attack:Class
# ./config/initializers/rack_attack.rb:15:in `<class:Attack>'
```

**Comment by corroded** [comment]
Sorry ignore me. I was looking at the code in `master` - some of which has not been released into `6-stable`. My bad!

**Comment by doutatsu** [comment]
@corroded so you are fine? I have been working on a different project and didn't have time to investigate this further yet

**Comment by corroded** [comment]
@doutatsu sorry same was busy haha but yeah I am fine. I just had to point to master instead of the released version :)

**Comment by grzuy** [comment]
Closing for lack of information to further triage the problem.

@doutatsu  Happy to re-open if we get more information.

Thanks for reporting.
