### ISSUE TITLE
NoMethodError: undefined method blocklisted_callback= for Rack::Attack:Class

### ISSUE THREAD

**Issue by christiannaths** [kickstarter/rack-attack#487]
I _think_ I found a bug, either in rack_attack or just in the readme. In following this example: https://github.com/kickstarter/rack-attack#customizing-responses, I added

```ruby
Rack::Attack.blocklisted_callback = lambda do |request|
  # Using 503 because it may make attacker think that they have successfully
  # DOSed the site. Rack::Attack returns 403 for blocklists by default
  [ 503, {}, ['Blocked']]
end
```

To my `config/initializers/rack_attack.rb` file. Here's the whole file:

```ruby
Rack::Attack.blocklist('php-bots') do |request|
  request.path.start_with?('/wp-') || /\S+\.php/.match?(request.path)
end

Rack::Attack.blocklisted_callback = ->(env) { [503, {}, %w[Blocked]] }

```

When starting the app, I get a

```
NoMethodError: undefined method `blocklisted_callback=' for Rack::Attack:Class
```

And when I inspect `Rack::Attack.methods` indeed it appears that `blocklisted_callback=` is not listed.

However, if I use `Rack::Attack.blocklisted_response` everything works as expected. Which is why I suspect this may just be a documentation issue.

---

<details>
  <summary>Full Stacktrace</summary>

```
[28764] ! Unable to load application: NoMethodError: undefined method `blocklisted_callback=' for Rack::Attack:Class
Did you mean?  blocklist_ip
~/Projects/my-rails-app/config/initializers/rack_attack.rb:7:in `<main>': undefined method `blocklisted_callback=' for Rack::Attack:Class (NoMethodError)
Did you mean?  blocklist_ip
	from ~/.gem/ruby/2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
	from ~/.gem/ruby/2.6.6/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
	from ~/.gem/ruby/2.6.6/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:319:in `block in load'
	from ~/.gem/ruby/2.6.6/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	from ~/.gem/ruby/2.6.6/gems/activesupport-6.0.2.2/lib/active_support/dependencies.rb:319:in `load'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/engine.rb:667:in `block in load_config_initializer'
	from ~/.gem/ruby/2.6.6/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb:182:in `instrument'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/engine.rb:666:in `load_config_initializer'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/engine.rb:624:in `block (2 levels) in <class:Engine>'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/engine.rb:623:in `each'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/engine.rb:623:in `block in <class:Engine>'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/initializable.rb:32:in `run'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/initializable.rb:50:in `each'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:415:in `call'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from ~/.rubies/ruby-2.6.6/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	from ~/.gem/ruby/2.6.6/gems/railties-6.0.2.2/lib/rails/application.rb:363:in `initialize!'
	from ~/Projects/my-rails-app/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from ~/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
	from ~/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
	from ~/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
	from ~/.gem/ruby/2.6.6/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
	from ~/.gem/ruby/2.6.6/gems/puma-4.3.3/lib/puma/configuration.rb:321:in `load_rackup'
	from ~/.gem/ruby/2.6.6/gems/puma-4.3.3/lib/puma/configuration.rb:246:in `app'
	from ~/.gem/ruby/2.6.6/gems/puma-4.3.3/lib/puma/runner.rb:155:in `load_and_bind'
	from ~/.gem/ruby/2.6.6/gems/puma-4.3.3/lib/puma/cluster.rb:413:in `run'
	from ~/.gem/ruby/2.6.6/gems/puma-4.3.3/lib/puma/launcher.rb:172:in `run'
	from ~/.gem/ruby/2.6.6/gems/puma-4.3.3/lib/puma/cli.rb:80:in `run'
	from ~/.gem/ruby/2.6.6/gems/puma-4.3.3/bin/puma:10:in `<top (required)>'
	from bin/puma:29:in `load'
	from bin/puma:29:in `<main>'
```

</details>

```
$ ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
```

```
$ rails -v
Rails 6.0.2.2
```

```
$ bundle info rack-attack
  * rack-attack (6.3.1)
	Summary: Block & throttle abusive requests
	Homepage: https://github.com/kickstarter/rack-attack
	Path: ~/.gem/ruby/2.6.6/gems/rack-attack-6.3.1
```

**Comment by grzuy** [comment]
> I _think_ I found a bug, either in rack_attack or just in the readme

Hi @christiannaths, I think you're viewing the `master` README, which documents `blocklisted_callback` not yet released.

You need to follow https://github.com/kickstarter/rack-attack/blob/6-stable/README.md.

We added a Note a the top of the `master` README, but maybe we need to add an emoji or something so that it's more visible.

Thanks.

**Comment by christiannaths** [comment]
Haha, wups! I knew something wasn't quite right; I completely missed that note 🤦‍♂️ Sorry for the trouble!

**Comment by madlew** [comment]
> Hi @christiannaths, I think you're viewing the `master` README, which documents `blocklisted_callback` not yet released.
> 
> You need to follow https://github.com/kickstarter/rack-attack/blob/6-stable/README.md.
> 
> We have a Note at the top of the `master` README, but maybe we need to add an emoji or something so that it's more visible.

so I find it really confusing

especially when I read:
> You are viewing the development's branch version of README which might contain documentation for unreleased features.

which here is described as 'development readme' and in the comment above as 'master redme', anyway it's different what is currently the latest released version

food for though: since you mentioned 'development' branch as a reference to ..master branch, why don't give https://danielkummer.github.io/git-flow-cheatsheet a try? and keep at master exactly what is actually released, and at develop branch what is still under development or completed but not yet released?

best,
lukasz

**Comment by grzuy** [comment]
Hey @madlew, thanks for the feedback, interesting.

So, in the hypothetical case of us using a `develop` branch, we would want GitHub setting `develop` branch as the default base branch for when contributors opening pull requests, meaning that we would need to set `develop` as the default branch in the repo settings. Wouldn't that also mean that it would be the default branch when visiting the repo landing page, meaning we wouldn't solve this problem?
